language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shawnmittal/docker-react-testing -f Dockerfile.dev .

script:
 - docker run -e CI=true USERNAME/docker-react-testing npm run test